In [1]:
l = [213, 235, 3434, -34534]

In [2]:
l

[213, 235, 3434, -34534]

In [3]:
import numpy as np

In [4]:
a = np.array(l)

In [5]:
a

array([   213,    235,   3434, -34534])

In [6]:
b = np.array([12, 235, 234.3, "True", "abc"])

In [7]:
b

array(['12', '235', '234.3', 'True', 'abc'], dtype='<U32')

In [8]:
l.pop()

-34534

In [9]:
l

[213, 235, 3434]

In [10]:
a.mean()

-7663.0

In [11]:
c = np.array([12, 23, True])

In [12]:
c

array([12, 23,  1])

In [13]:
d = np.array([12,345,36,"1"])

In [14]:
d

array(['12', '345', '36', '1'], dtype='<U21')

---

In [15]:
d[1:]

array(['345', '36', '1'], dtype='<U21')

In [16]:
e = [123,345,4574,21]

In [17]:
f = e[0]

In [18]:
e

[123, 345, 4574, 21]

In [19]:
f

123

In [20]:
e[0] = 9

In [21]:
e

[9, 345, 4574, 21]

In [22]:
f

123

In [23]:
f = e[1:2]

In [24]:
f

[345]

In [25]:
e

[9, 345, 4574, 21]

In [27]:
e[1] = 55

In [28]:
e

[9, 55, 4574, 21]

In [29]:
f

[345]

In [30]:
f[0] = 77

In [31]:
e

[9, 55, 4574, 21]

In [32]:
f

[77]

---

In [33]:
h = np.array([234,236,13,6787,234,454,3453,55,6,79,679,23,42,1])

In [34]:
h

array([ 234,  236,   13, 6787,  234,  454, 3453,   55,    6,   79,  679,
         23,   42,    1])

In [35]:
r = h[5:9]

In [36]:
r

array([ 454, 3453,   55,    6])

In [37]:
r[2] = 20

In [38]:
r

array([ 454, 3453,   20,    6])

In [39]:
h

array([ 234,  236,   13, 6787,  234,  454, 3453,   20,    6,   79,  679,
         23,   42,    1])

In [40]:
j = h.copy()

In [41]:
j

array([ 234,  236,   13, 6787,  234,  454, 3453,   20,    6,   79,  679,
         23,   42,    1])

In [42]:
j[0] = 0

In [43]:
h

array([ 234,  236,   13, 6787,  234,  454, 3453,   20,    6,   79,  679,
         23,   42,    1])

In [44]:
j

array([   0,  236,   13, 6787,  234,  454, 3453,   20,    6,   79,  679,
         23,   42,    1])