In [4]:
import numpy as np
mydata = np.arange(0, 20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
np.reshape(mydata, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
matr1 = np.reshape(mydata, (5,4), order="C")
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
matr2 = np.reshape(mydata, (5,4), order="F")
matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

---

In [9]:
# Exercise - Get to the number 10

In [11]:
print(matr1[2,2])

10


In [14]:
print(matr2[0, 2])

10


---

In [15]:
# OOP Concept

In [17]:
# np.reshape(mydata, (5,4))
mydata.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [18]:
# ---- np.array

In [20]:
r1 = ["I", "am", "happy"]
r2 = ["What", "a", "day"]
r3 = [1, 2, 3]

In [22]:
[r1, r2, r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [25]:
np.array([r1, r2, r3])

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U21')

In [27]:
print(np.array([r1, r2, r3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]
